version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-client:
    executor:
      name: node/default
    working_directory: ~/client
    steps:
      - checkout:
          path: "~"
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  build-and-test-server:
    executor:
      name: node/default
    working_directory: ~/server
    steps:
      - checkout:
          path: "~"
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test-client
        - build-and-test-server
