version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-client:
    executor:
      name: node/default
    working_directory: ~/repo/client
    steps:
      - checkout:
          path: ~/repo
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  build-and-test-server:
    executor:
      name: node/default
    working_directory: ~/repo/server
    steps:
      - checkout:
          path: ~/repo
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  build-docker-client:
    machine: true
    working_directory: ~/repo/client
    steps:
      - checkout:
          path: ~/repo
      - run: 'echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin'
      - run: docker build -t $DOCKER_USER/client:$CIRCLE_BRANCH .
      - run: docker push $DOCKER_USER/client:$CIRCLE_BRANCH
  build-docker-server:
    machine: true
    working_directory: ~/repo/server
    steps:
      - checkout:
          path: ~/repo
      - run: 'echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin'
      - run: docker build -t $DOCKER_USER/server:$CIRCLE_BRANCH .
      - run: docker push $DOCKER_USER/server:$CIRCLE_BRANCH
workflows:
    build-test-deploy:
      jobs:
        - build-and-test-client
        - build-and-test-server
        - build-docker-client:
            requires:
              - build-and-test-client
              - build-and-test-server
        - build-docker-server:
            requires:
              - build-and-test-client
              - build-and-test-server
